# Generated by Django 3.1.4 on 2021-02-17 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_client', models.BooleanField(default=False, verbose_name='Estado de cliente')),
                ('is_mechanic', models.BooleanField(default=False, verbose_name='Estado de mecanico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='coches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('colour', models.CharField(max_length=50, verbose_name='Color')),
                ('dateM', models.DateField(verbose_name='Fecha de Matriculacion')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Coche ',
                'verbose_name_plural': 'Coches',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente', serialize=False, to='nucleo.usernucleo')),
                ('DNI', models.CharField(max_length=50, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=75, verbose_name='Direccion')),
                ('tel', models.CharField(max_length=30, verbose_name='Telefono')),
                ('date', models.DateField(verbose_name='FechaNacimiento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='mecanicos',
            fields=[
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mecanico', serialize=False, to='nucleo.usernucleo')),
                ('DNI', models.CharField(max_length=50, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direction', models.CharField(max_length=75, verbose_name='Direccion')),
                ('tel', models.CharField(max_length=30, verbose_name='Telefono')),
                ('date', models.DateField(verbose_name='FechaNacimiento')),
            ],
            options={
                'verbose_name': 'Mecanico',
                'verbose_name_plural': 'Mecanicos',
            },
        ),
        migrations.CreateModel(
            name='reparaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateR', models.DateTimeField(auto_now_add=True, verbose_name='FechaSolicitud')),
                ('dateA', models.DateTimeField(auto_now=True, null=True, verbose_name='FechaArreglo')),
                ('reason', models.CharField(max_length=300, verbose_name='Motivo')),
                ('observations', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('fixed', models.BooleanField(null=True, verbose_name='Arreglado')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='nucleo.coches', verbose_name='Coche')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='nucleo.clientes', verbose_name='Cliente')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='nucleo.mecanicos', verbose_name='Mecanico')),
            ],
            options={
                'verbose_name': 'Reparacion',
                'verbose_name_plural': 'Reparaciones',
            },
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('text', models.CharField(max_length=200, verbose_name='Texto')),
                ('photo', models.ImageField(upload_to='News/%Y/%m/%d', verbose_name='Foto')),
                ('dateC', models.DateField(auto_now_add=True, verbose_name='FechaCreacion')),
                ('dateU', models.DateField(auto_now=True, verbose_name='FechaModificacion')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='nucleo.mecanicos', verbose_name='Mecanico')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AddField(
            model_name='coches',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='nucleo.clientes', verbose_name='Cliente'),
        ),
    ]
